name: Kvaesitso Tasks.org plugin
summary: A plugin for Kvaesitso that lets you search tasks in the Tasks.org app
license: Apache-2.0
author:
    name: MM20
website: https://kvaesitso.mm20.de
source: https://github.com/Kvaesitso/Plugin-TasksOrg
issues: https://github.com/Kvaesitso/Plugin-TasksOrg/issues
translation: https://i18n.mm20.de/engage/kvaesitso/
donate: https://github.com/sponsors/MM2-0
categories:
    - System
