name: Kvaesitso Plugin for Breezy Weather
summary: A plugin for Kvaesitso that enables the launcher to use weather data from Breezy Weather
license: Apache-2.0
author:
    name: MM20
website: https://kvaesitso.mm20.de
source: https://github.com/Kvaesitso/Plugin-BreezyWeather
issues: https://github.com/Kvaesitso/Plugin-BreezyWeather/issues
translation: https://i18n.mm20.de/engage/kvaesitso/
donate: https://github.com/sponsors/MM2-0
categories:
    - System
antiFeatures:
    - NonFreeNet
