name: Public transport plugin for Kvaesitso
summary: This plugin enables querying your local public transport providers for stops and departures near you.
license: GPL-3.0
author:
    name: Sir-Photch
website: https://github.com/Sir-Photch/KvaesitsoPlugin-PublicTransport
source: https://github.com/Sir-Photch/KvaesitsoPlugin-PublicTransport
issues: https://github.com/Sir-Photch/KvaesitsoPlugin-PublicTransport/issues
translation: https://hosted.weblate.org/engage/kvaesitsoplugin-publictransport/
categories:
    - System
antiFeatures:
    - NonFreeNet
